<template>
    <q-page class="privacy-page">
      <div class="row justify-center">
        <div class="col-6 col-12-xs">
<div class="cuartodiv-col">
   <!----> 
   <div class="tucupampam" style="z-index: 100;">
      <h1 style="margin-top: 10px;">Privacy Policy</h1>
      <p>Updated at 2021-04-17</p>
      <p style="display: inline;"> CloseTab</p>
      <p class="p4" style="display: inline;"><span class="s1">("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by</span></p>
      <p style="display: inline;"> CloseTab.</p>
      <br> 
      <div style="display: inline;">
         <p style="display: inline;"><span class="s1">This Privacy Policy applies to our website,</span></p>
         <p style="display: inline;"><span class="s1"> https://closetab.email</span></p>
         <p style="display: inline;"><span class="s1">, and its associated subdomains (collectively, our "Service").</span></p>
      </div>
      <p style="display: inline;"><span class="s1">By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</span></p>
      <p class="p6"><br></p>
      <h1>Definitions and key terms</h1>
      <p class="p8"><span class="s1">For this Privacy Policy:</span></p>
      <p class="p9"><br></p>
      <ul class="ul1">
         <li class="li8"><span class="s1"><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br></span></li>
         <!----> 
         <li class="li8"><span class="s1"><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to <a>CloseTab</a> that is responsible for your information under this Privacy Policy.<br></span></li>
         <li class="li8"><span class="s1"><strong>Country:</strong> where <a>CloseTab</a> or the owners/founders of <a>CloseTab</a> are based, in this case is <a>India</a>.<br></span></li>
         <li class="li8"><span class="s1"><strong>Customer:</strong> refers to the company, organization or person that signs up to use the <a>CloseTab</a> Service to manage the relationships with your consumers or service users.<br></span></li>
         <li class="li8"><span class="s1"><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit <a>CloseTab</a> and use the services.<br></span></li>
         <li class="li8"><span class="s1"><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.<br></span></li>
         <li class="li8"><span class="s1"><strong>Personnel:</strong> refers to those individuals who are employed by <a>CloseTab</a> or are under contract to perform a service on behalf of one of the parties.<br></span></li>
         <li class="li8"><span class="s1"><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.<br></span></li>
         <li class="li8"><span class="s1"><strong>Service:</strong> refers to the service provided by <a>CloseTab</a> as described in the relative terms (if available) and on this platform.<br></span></li>
         <li class="li8"><span class="s1"><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.<br></span></li>
         <li class="li8"><span class="s1"><strong>Website:</strong> <a>CloseTab</a>’s site, which can be accessed via this URL: <a>https://closetab.email.</a><br></span></li>
         <li class="li8"><span class="s1"><strong>You:</strong> a person or entity that is registered with <a>CloseTab</a> to use the Services.<br></span></li>
      </ul>
      <p class="p9"><br></p>
      <div>
         <h1>What Information Do We Collect?</h1>
         <p class="p10"><span class="s1">We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</span></p>
         <ul class="ul1">
            <li class="li11"><span class="s3">Name / Username</span></li>
            <!----> 
            <li class="li11"><span class="s3">Email Addresses</span></li>
            <!----> <!----> <!----> <!----> <!----> <!---->
         </ul>
      </div>
      <p class="p12"><br></p>
      <!----> <!----> 
      <p class="p3"><br></p>
      <h1>How Do We Use The Information We Collect?</h1>
      <p class="p10"><span class="s1">Any of the information we collect from you may be used in one of the following ways:</span></p>
      <ul class="ul1">
         <li class="li11"><span class="s3">To personalize your experience (your information helps us to better respond to your individual needs)</span></li>
         <li class="li11"><span class="s3">To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</span></li>
         <li class="li11"><span class="s3">To process transactions</span></li>
         <li class="li11"><span class="s3">To send periodic emails</span></li>
      </ul>
      <p class="p3"><br></p>
      <h1>When do we use customer information from third parties?</h1>
      <p class="p10"><span class="s1">We collect the public display name and the registered email address when the user signs-in with the corresponding third party (Google, Twitter)</span></p>
      <p class="p3"><br></p>
      <h1>Do we share the information we collect with third parties?</h1>
      <p class="p10">
        This website is free of Google tracker. We do not share any information with any third parties.
      </p>
      <p class="p3"><br></p>
      <h1>Where and when is information collected from customers and end users?</h1>
      <p class="p10"> We collect the aforementioned information about the user at the time of signing-in using those thirdy parties.</p>
      <p class="p3"><br></p>
      <h1>How Do We Use Your Email Address?</h1>
      <p class="p10"><span class="s1">By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</span></p>
      <p class="p3"><br></p>
      <h1>Could my information be transferred to other countries?</h1>
      <p class="p10"><span class="s1">We are incorporated in India. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries
         that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans- border transfer and hosting of such information.</span>
      </p>
      <p class="p3"><br></p>
      <h1>Is the information collected through our service secure?</h1>
      <p class="p10"><span class="s1">We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</span></p>
      <p class="p3"><br></p>
      <h1>How Long Do We Keep Your Information?</h1>
      <p class="p10"><span class="s1">We keep your information only so long as we need it to provide service to you and fulfill the purposes described in this policy. When a user deletes his/her account from our service all information of that user is removed permanently.</span></p>
      <p class="p3"><br></p>
      <h1>How Do We Protect Your Information?</h1>
      <p class="p10"><span class="s1">We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</span></p>
      <p class="p3"><br></p>
      <h1>Governing Law</h1>
      <p class="p10"><span class="s1">The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of our service. Your use of our service may also be subject to other local, state, national, or international laws.</span></p>
      <p class="p3"><br></p>
      <h1>Your Consent</h1>
      <p class="p10"><span class="s1">By using our service, registering an account, or making a purchase, you consent to this Privacy Policy.</span></p>
      <p class="p3"><br></p>
      <h1>Links to Other Websites</h1>
      <p class="p10"><span class="s1">This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by . We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</span></p>
      <p class="p3"><br></p>
      <h1>Cookies</h1>
      <p class="p10"><span class="s1">We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</span></p>
      <p class="p3"><br></p>
      <!----> <!----> <!----> <!----> <!----> 
      <p class="p15"><br></p>
      <!----> <!----> <!----> <!----> <!----> <!----> 
      <!----> <!----> <!----> 
      <h1>Changes To Our Privacy Policy</h1>
      <p class="p10"><span class="s1">If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.</span></p>
      <p class="p3"><br></p>
      <h1>Third-Party Services</h1>
      <p class="p10"><span class="s1">We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</span></p>
      <p class="p10"><span class="s1">You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</span></p>
      <p class="p10"><span class="s1">Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</span></p>
      <p class="p3"><br></p>
      <h1>Tracking Technologies</h1>
      <!----> <!----> 
      <li class="li11"><span class="s3">Cookies</span></li>
      <p class="p10"><span class="s1">
         We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your
         login details every time you visit our service as we would not be able to remember that you had logged in previously.
         </span>
      </p>
      <li class="li11"><span class="s3">Local Storage</span></li>
      <p class="p10"><span class="s1">
         Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.
         </span>
      </p>
      <li class="li11"><span class="s3">Sessions</span></li>
      <p class="p10"><span class="s1">
         We use "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.
         </span>
      </p>
      <p class="p3"><br></p>
      <h1>Information about General Data Protection Regulation (GDPR)</h1>
      <p class="p10"><span class="s1">We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.</span></p>
      <p class="p12"><br></p>
      <h1>What is GDPR?</h1>
      <p class="p10">
         <span class="s1">
            GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have, over their personal data.
      <p class="p12"><br></p> <h1>What is personal data?</h1> <p class="p10"><span class="s1">Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity.
      The Data Protection Principles include requirements such as:</span></p> <ul class="ul1"><li class="li11"><span class="s3">Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</span></li> <li class="li11"><span class="s3">Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</span></li> <li class="li11"><span class="s3">Personal data should be held no longer than necessary to fulfil its purpose.</span></li> <li class="li11"><span class="s3">People covered by the GDPR have the right to access their own personal data.
      They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</span></li></ul> <p class="p12"><br></p> <h1>Why is GDPR important?</h1> <p class="p10"><span class="s1">GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts it's simply the right thing to do. At Help Scout we strongly believe that your data privacy is very important and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.</span></p> <p class="p12"><br></p> <h1>Individual Data Subject's Rights - Data Access, Portability and Deletion</h1> <p class="p10"><span class="s1">We are committed to helping our customers meet the data subject rights requirements of GDPR. We process or store all personal data in fully vetted, DPA compliant vendors. We do store
      all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.
      <br><br>
      We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self service from the start and have always given you access to your data and your customers data. Our customer support team is here for you to answer any questions you might have about working with the API.</span></p> <p class="p3"><br></p> <h1>California Residents</h1> <p class="p15"><br></p> <p class="p10"><span class="s1">The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</span></p> <p class="p10"><span class="s1">We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:</span></p> <ul class="ul1"><li class="li11"><span class="s3">Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</span></li> <li class="li11"><span class="s3">Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</span></li> <li class="li11"><span class="s3">Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</span></li> <li class="li11"><span class="s3">Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</span></li></ul> <p class="p12"><br></p> <p class="p10"><span class="s1">If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</span></p> <p class="p10"><span class="s1">We do not sell the Personal Information of our users.</span></p> <p class="p10"><span class="s1">For more information about these rights, please contact us.</span></p> <p class="p3"><br></p> <h1>California Online Privacy Protection Act (CalOPPA)</h1> <p class="p10"><span class="s1">CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</span></p> <p class="p10"><span class="s1">CalOPPA users have the following rights:</span></p> <ul class="ul1"><li class="li11"><span class="s3">Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</span></li> <li class="li11"><span class="s3">Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</span></li> <li class="li11"><span class="s3">Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</span></li> <li class="li11"><span class="s3">Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</span></li></ul> <p class="p12"><br></p> <p class="p10"><span class="s1">If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
      <br><br>
      We do not sell the Personal Information of our users.
      <br><br>
      For more information about these rights, please contact us.</span></p> <p class="p3"><br></p> <h1>Contact Us</h1> <p class="p10"><span class="s1">Don't hesitate to contact us if you have any questions.</span></p> <ul class="ul1"><li class="li16"><span class="s3">Via Email: <a>joe@closetab.email</a></span></li> <!----> <!----> <!----></ul></span></p>
   </div>
</div>

        </div>
      </div>
    </q-page>
</template>
<style scoped>
.privacy-page h1 {
  font-size: 20px;
  font-weight: bolder;
}
</style>